### ISSUE TITLE
flannel CNI plugin doesn't support chaining

### ISSUE THREAD

**Issue by tomdee** [containernetworking/plugins#43] opened 2017-07-14 17:29 UTC
See this issue https://github.com/coreos/flannel/issues/772

**Comment by wzhliang** [comment] 2017-07-17 08:03
With 0.6.0 rc1 binary this is working. Perhaps a package error with Centos.

**Comment by squeed** [comment] 2017-07-24 16:18
Probably a dupe of #23?

**Comment by wzhliang** [comment] 2017-07-25 00:06
this is OK as mentioned. please close.

**Closed** 2017-07-25 21:10 UTC
